# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webpack - Website
email: jgatjens@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an experienced Software Developer based in the Costa Rica.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jgatjens.github.io" # the base hostname & protocol for your site
twitter_username: jgatjens
github_username: jgatjens
linkedin_username: jgatjens
# Build settings
markdown: kramdown

# Build settings
gems:
  - octopress-minify-html